const students = [
    {
      id: 1,      
      first_name: "John",
      last_name: "Doe",
      email: "john.doe",
      phone: "89998739",
      year_group: "Grade 10",
      photo: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
      id: 2,      
      first_name: "Jane",
      last_name: "Doe",
      email: "jane.doe",
      phone: "12333339",
      year_group: "Grade 10",
      photo: "https://randomuser.me/api/portraits/women/1.jpg",
    },
    {
      id: 3,      
      first_name: "John",
      last_name: "Doe",
      email: "john.doe",
      phone: "123429989",
      year_group: "Grade 12",
      photo: "https://randomuser.me/api/portraits/men/2.jpg",
    },
    {
      id: 4,      
      first_name: "Jane",
      last_name: "Doe",
      email: "jane.doe",
      phone: "00000099",
      year_group: "Grade 11",
      photo: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    {
      id: 5,      
      first_name: "John",
      last_name: "Doe",
      email: "john.doe",
      phone: "82929999",
      year_group: "Grade 12",
      photo: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
      id: 6,      
      first_name: "Jane",
      last_name: "Doe",
      email: "jane.doe",
      phone: "98888887",
      year_group: "Grade 12",
      photo: "https://randomuser.me/api/portraits/women/3.jpg",
    },
    {
      id: 7,      
      first_name: "John",
      last_name: "Doe",
      email: "john.doe",
      phone: "123456789",
      year_group: "Grade 12",
      photo: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
      id: 8,      
      first_name: "Jane",
      last_name: "Doe",
      email: "jane.doe",
      phone: "123456789",
      year_group: "Grade 12",
      photo: "https://randomuser.me/api/portraits/women/4.jpg",
    },
    {
      id: 9,      
      first_name: "John",
      last_name: "Doe",
      email: "john.doe",
      phone: "123456789",
      year_group: "Grade 12",
      photo: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
      id: 10,      
      first_name: "Jane",
      last_name: "Doe",
      email: "jane.doe",
      phone: "123456789",
      year_group: "Grade 12",
      photo: "https://randomuser.me/api/portraits/women/5.jpg",
    }
  
  ]


export default students;